import Head from 'next/head';
import { useStyles } from '@/pages/styles';

// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
// Usage example
// <h2 className={inter.className}>

export default function Home() {
  const { root } = useStyles();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={root}></main>
    </>
  );
}
